CREATE TABLE IF NOT EXISTS "users"
(
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    username   VARCHAR(100) NOT NULL UNIQUE,
    email      VARCHAR(150) UNIQUE
); -- создание таблицы user

drop table "users";

SELECT  * FROM users;